os: windows
language: python
sudo: required
python:
  - "3.7"
  
services:
  - postgresql
env:
  - DJANGO_VERSION=2.2.8
branches:
    only:
        - master
# command to install dependencies
before_install:
  - sudo service postgresql restart
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script:
  - py manage.py test
