dist: xenial
language: python
sudo: required
python:
  - "3.7"
  
services:
  - postgresql
env:
  - DJANGO_VERSION=2.2.8
branches:
    only:
        - master
# command to install dependencies
before_install:
  - sudo service postgresql restart
install:
  - pip install -r requirements.txt
before_script:
  - postgresql -e 'CREATE DATABASE `djangoblogdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;'
  - py manage.py makemigrations
  - py manage.py migrate
# command to run tests
script:
  - py manage.py test
